### ISSUE TITLE
Declaring and showing custom types

### ISSUE THREAD

**Issue by tingerrr** [jneug/typst-mantys#11]
It would be great if one could register their own custom types that would be included in the theme.

In hydra, I have a section detailing dictionaries of certain shape that I pass around for internal use, and I give them names to use in the tidy doc-strings. These are currently not highlighted at all and if they were, I couldn't add my own `dtype` colors to the internal mantys theme.

Separately, it would be great if mantys had a canonical way to show custom types in the reference somewhere.

Mine currently look like this:
![image](https://github.com/jneug/typst-mantys/assets/137803093/0c3f6575-13b7-4bfc-b4d5-4d1736cb1ca5)
And used like this:
![image](https://github.com/jneug/typst-mantys/assets/137803093/a43e513e-d7d0-4433-bbb1-ca5524560838)

In the future, this will likely be superseded by actual types, but they too will need some kind of dedicated display function.

**Comment by jneug** [comment]
The idea is to have the type "context" link to a section in the manual that defines the structure of this dictionary? 

Is there any other use-case for custom "types" other than dictionaries with some specific keys?

**Comment by jneug** [comment]
I added this to the main branch in this repository. Maybe you want to try it out.

Just call `#add-type` to add a custom type and optionally give it a color and a target that is passed to `#link'.

```typst
#add-type("queryable", target:label("type-queryable"), color:rgb("#cd716b"))

#dtype("queryable")
```

**Comment by tingerrr** [comment]
I've tried it out, works great.

**Comment by tingerrr** [comment]
Closing as completed.
