### ISSUE TITLE
Release as a template

### ISSUE THREAD

**Issue by tingerrr** [jneug/typst-mantys#3]
With Typst `0.11.0` and Typst Universe, template packages are now accepted in the package repository.

I'd love to use this for my packages to get a clean and uniform look, but I'm not exactly thrilled about installing it locally, especially because this needlessly complicates my CI workflows too.

If you don't have time to prep this for release as a template, I'd be happy to write a PR that makes it template-ready.

**Comment by jneug** [comment]
Thanks for your input. I'm definitely going to do this. Currently, I'm working on updating some of my other packages to 0.11, but after that, I will take a look at Mantys.

**Comment by jneug** [comment]
Actually, I decided to just publish the current version right away. 

I want to do some work on the template, but I can still do that after it is published, I guess. 

It should be available in the next few days.
